name: Cypress E2E

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - dev
    workflow_dispatch:

env:
    # User specified
    REACT_APP_BACKEND_URL: https://staging.lb.knowit-anonymous-voting-app.aws.cybercom.dev

    # Secrets
    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

    # Automatic
    GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
    GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
    GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    cypress-run-ubuntu:
        name: Run cypress on Ubuntu 22.04
        runs-on: ubuntu-22.04
        strategy:
            fail-fast: false
            matrix:
                browser: [chrome, edge]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@main
              with:
                  node-version: lts/*
                  cache: npm

            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  working-directory: frontend
                  browser: ${{ matrix.browser }}
                  record: true
                  spec: cypress/e2e/*

    cypress-run-windows:
        name: Run cypress on Windows Server 2022
        runs-on: windows-2022
        strategy:
            fail-fast: false
            matrix:
                browser: [chrome, firefox, edge]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@main
              with:
                  node-version: lts/*
                  cache: npm

            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  working-directory: frontend
                  browser: ${{ matrix.browser }}
                  record: true
                  spec: cypress/e2e/*

    cypress-run-macos:
        name: Run cypress on MacOS 12
        runs-on: macos-12
        strategy:
            fail-fast: false
            matrix:
                browser: [chrome, firefox, edge]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@main
              with:
                  node-version: lts/*
                  cache: npm

            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                  working-directory: frontend
                  browser: ${{ matrix.browser }}
                  record: true
                  spec: cypress/e2e/*
